INSERT INTO proficiencies (name, base_attribute) VALUES ('Акробатика', 'DEXTERITY');
INSERT INTO proficiencies (name, base_attribute) VALUES ('Атлетика', 'STRENGTH');
INSERT INTO proficiencies (name, base_attribute) VALUES ('Аркана', 'INTELLIGENCE');
INSERT INTO proficiencies (name, base_attribute) VALUES ('Обман', 'CHARISMA');
INSERT INTO proficiencies (name, base_attribute) VALUES ('История', 'INTELLIGENCE');
INSERT INTO proficiencies (name, base_attribute) VALUES ('Проницательность', 'WISDOM');
INSERT INTO proficiencies (name, base_attribute) VALUES ('Запугивание', 'CHARISMA');
INSERT INTO proficiencies (name, base_attribute) VALUES ('Расследование', 'INTELLIGENCE');
INSERT INTO proficiencies (name, base_attribute) VALUES ('Медицина', 'WISDOM');
INSERT INTO proficiencies (name, base_attribute) VALUES ('Природа', 'INTELLIGENCE');
INSERT INTO proficiencies (name, base_attribute) VALUES ('Внимательность', 'WISDOM');
INSERT INTO proficiencies (name, base_attribute) VALUES ('Выступление', 'CHARISMA');
INSERT INTO proficiencies (name, base_attribute) VALUES ('Убеждение', 'CHARISMA');
INSERT INTO proficiencies (name, base_attribute) VALUES ('Религия', 'INTELLIGENCE');
INSERT INTO proficiencies (name, base_attribute) VALUES ('Ловкость рук', 'DEXTERITY');
INSERT INTO proficiencies (name, base_attribute) VALUES ('Скрытность', 'DEXTERITY');
INSERT INTO proficiencies (name, base_attribute) VALUES ('Выживание', 'WISDOM');
INSERT INTO proficiencies (name, base_attribute) VALUES ('Обращение с животными', 'WISDOM');

INSERT INTO classes (name, saving_throw_one, saving_throw_two) VALUES ('Бард', 'DEXTERITY', 'CHARISMA');
INSERT INTO classes (name, saving_throw_one, saving_throw_two) VALUES ('Варвар', 'STRENGTH', 'CONSTITUTION');
INSERT INTO classes (name, saving_throw_one, saving_throw_two) VALUES ('Воин', 'STRENGTH', 'CONSTITUTION');
INSERT INTO classes (name, saving_throw_one, saving_throw_two) VALUES ('Волшебник', 'INTELLIGENCE', 'WISDOM');
INSERT INTO classes (name, saving_throw_one, saving_throw_two) VALUES ('Друид', 'INTELLIGENCE', 'WISDOM');
INSERT INTO classes (name, saving_throw_one, saving_throw_two) VALUES ('Изобретатель', 'CONSTITUTION', 'INTELLIGENCE');
INSERT INTO classes (name, saving_throw_one, saving_throw_two) VALUES ('Колдун', 'WISDOM', 'CHARISMA');
INSERT INTO classes (name, saving_throw_one, saving_throw_two) VALUES ('Кровавый охотник', 'DEXTERITY', 'INTELLIGENCE');
INSERT INTO classes (name, saving_throw_one, saving_throw_two) VALUES ('Монах', 'STRENGTH', 'DEXTERITY');
INSERT INTO classes (name, saving_throw_one, saving_throw_two) VALUES ('Паладин', 'WISDOM', 'CHARISMA');
INSERT INTO classes (name, saving_throw_one, saving_throw_two) VALUES ('Плут', 'DEXTERITY', 'INTELLIGENCE');
INSERT INTO classes (name, saving_throw_one, saving_throw_two) VALUES ('Следопыт', 'STRENGTH', 'DEXTERITY');
INSERT INTO classes (name, saving_throw_one, saving_throw_two) VALUES ('Чародей', 'CONSTITUTION', 'CHARISMA');