DROP table IF EXISTS users CASCADE;
DROP table IF EXISTS classes CASCADE;
DROP table IF EXISTS characters CASCADE;
DROP table IF EXISTS proficiencies CASCADE;
DROP table IF EXISTS proficiencies CASCADE;
DROP table IF EXISTS characters_proficiencies CASCADE;
DROP table IF EXISTS characters_classes CASCADE;

CREATE table IF NOT EXISTS users (
    id          BIGINT  GENERATED BY DEFAULT AS IDENTITY    NOT NULL,
    name        VARCHAR                                     NOT NULL,
    password    VARCHAR                                     NOT NULL,
    email       VARCHAR                                     NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
    );

CREATE table IF NOT EXISTS classes (
    id                  BIGINT  GENERATED BY DEFAULT AS IDENTITY   NOT NULL,
    name                VARCHAR                                    NOT NULL,
    saving_throw_one    VARCHAR                                    NOT NULL,
    saving_throw_two    VARCHAR                                    NOT NULL,
    CONSTRAINT pk_classes PRIMARY KEY (id)
    );

CREATE table IF NOT EXISTS characters (
    id              BIGINT  GENERATED BY DEFAULT AS IDENTITY   NOT NULL,
    name            VARCHAR                                    NOT NULL,
    race            VARCHAR                                    NOT NULL,
    strength        BIGINT                                     NOT NULL,
    dexterity       BIGINT                                     NOT NULL,
    constitution    BIGINT                                     NOT NULL,
    intelligence    BIGINT                                     NOT NULL,
    wisdom          BIGINT                                     NOT NULL,
    charisma        BIGINT                                     NOT NULL,
    experience      BIGINT                                     NOT NULL,
    armor_class     BIGINT                                     NOT NULL,
    speed           BIGINT                                     NOT NULL,
    initiative      BIGINT                                     NOT NULL,
    max_hp          BIGINT                                     NOT NULL,
    current_hp      BIGINT                                     NOT NULL,
    creator_id      BIGINT                                     NOT NULL REFERENCES users (id),
    CONSTRAINT pk_characters PRIMARY KEY (id)
    );

CREATE table IF NOT EXISTS proficiencies (
    id              BIGINT  GENERATED BY DEFAULT AS IDENTITY    NOT NULL,
    name            VARCHAR                                     NOT NULL,
    base_attribute  VARCHAR                                             ,
    CONSTRAINT pk_proficiencies PRIMARY KEY (id)
    );

create table if not exists characters_proficiencies (
    fk_character       bigint not null references characters (id),
    fk_proficiency     bigint not null references proficiencies (id)
    );

create table if not exists characters_classes (
    fk_character    bigint not null references characters (id),
    fk_class        bigint not null references classes (id)
    );