DROP table IF EXISTS users CASCADE;
DROP table IF EXISTS races CASCADE;
DROP table IF EXISTS classes CASCADE;
DROP table IF EXISTS abilities CASCADE;
DROP table IF EXISTS characters CASCADE;
DROP table IF EXISTS proficiencies CASCADE;
DROP table IF EXISTS characters_proficiencies CASCADE;
DROP table IF EXISTS characters_classes CASCADE;

CREATE table IF NOT EXISTS users (
    id          BIGINT  GENERATED BY DEFAULT AS IDENTITY    NOT NULL,
    name        VARCHAR                                     NOT NULL,
    password    VARCHAR                                     NOT NULL,
    email       VARCHAR                                     NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
    );

CREATE table IF NOT EXISTS races (
    id                  BIGINT  GENERATED BY DEFAULT AS IDENTITY    NOT NULL,
    name                VARCHAR                                     NOT NULL,
    size                VARCHAR                                     NOT NULL,
    speed               INTEGER                                     NOT NULL,
    has_darkvision      BOOLEAN                                     NOT NULL,
    strength_bonus      INTEGER,
    dexterity_bonus     INTEGER,
    constitution_bonus  INTEGER,
    intelligence_bonus  INTEGER,
    wisdom_bonus        INTEGER,
    charisma_bonus      INTEGER,
    CONSTRAINT pk_races PRIMARY KEY (id)
    );

CREATE table IF NOT EXISTS classes (
    id                  BIGINT  GENERATED BY DEFAULT AS IDENTITY   NOT NULL,
    name                VARCHAR                                    NOT NULL,
    saving_throw_one    VARCHAR                                    NOT NULL,
    saving_throw_two    VARCHAR                                    NOT NULL,
    CONSTRAINT pk_classes PRIMARY KEY (id)
    );

CREATE table IF NOT EXISTS abilities (
    id              BIGINT  GENERATED BY DEFAULT AS IDENTITY   NOT NULL,
    name            VARCHAR                                    NOT NULL,
    description     VARCHAR                                    NOT NULL,
    char_class_id   BIGINT                                     NOT NULL REFERENCES classes (id),
    class_level     INTEGER                                    NOT NULL,
    is_active       BOOLEAN                                    NOT NULL,
    cost            VARCHAR                                    NOT NULL,
    requires_rest   BOOLEAN                                    NOT NULL,
    type_of_rest    VARCHAR                                    NOT NULL,
    CONSTRAINT pk_abilities PRIMARY KEY (id)
    );

CREATE table IF NOT EXISTS characters (
    id              BIGINT  GENERATED BY DEFAULT AS IDENTITY   NOT NULL,
    name            VARCHAR                                    NOT NULL,
    race_id         BIGINT                                     NOT NULL REFERENCES races (id),
    strength        INTEGER                                    NOT NULL,
    dexterity       INTEGER                                    NOT NULL,
    constitution    INTEGER                                    NOT NULL,
    intelligence    INTEGER                                    NOT NULL,
    wisdom          INTEGER                                    NOT NULL,
    charisma        INTEGER                                    NOT NULL,
    experience      BIGINT                                     NOT NULL,
    armor_class     INTEGER                                    NOT NULL,
    initiative      INTEGER                                    NOT NULL,
    max_hp          INTEGER                                    NOT NULL,
    current_hp      INTEGER                                    NOT NULL,
    creator_id      BIGINT                                     NOT NULL REFERENCES users (id),
    CONSTRAINT pk_characters PRIMARY KEY (id)
    );

CREATE table IF NOT EXISTS proficiencies (
    id              BIGINT  GENERATED BY DEFAULT AS IDENTITY    NOT NULL,
    name            VARCHAR                                     NOT NULL,
    base_attribute  VARCHAR                                             ,
    CONSTRAINT pk_proficiencies PRIMARY KEY (id)
    );

create table if not exists characters_proficiencies (
    fk_character       bigint not null references characters (id),
    fk_proficiency     bigint not null references proficiencies (id)
    );

create table if not exists characters_classes (
    fk_character    bigint not null references characters (id),
    fk_class        bigint not null references classes (id)
    );

create table if not exists classes_abilities (
    fk_character    bigint not null references characters (id),
    fk_class        bigint not null references classes (id),
    number_of_uses  integer
    );