/*DROP table IF EXISTS users CASCADE;
DROP table IF EXISTS races CASCADE;
DROP table IF EXISTS classes CASCADE;
DROP table IF EXISTS abilities CASCADE;
DROP table IF EXISTS characters CASCADE;
DROP table IF EXISTS proficiencies CASCADE;
DROP table IF EXISTS characters_proficiencies CASCADE;
DROP table IF EXISTS characters_classes CASCADE;
DROP table IF EXISTS character_classes_abilities CASCADE;
DROP table IF EXISTS character_race_abilities CASCADE;
DROP table IF EXISTS character_classes_level CASCADE;
DROP table IF EXISTS subclasses CASCADE;
*/

--liquibase formatted sql
--changeset users:1

CREATE table IF NOT EXISTS users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR                                 NOT NULL,
    password VARCHAR                                 NOT NULL,
    email    VARCHAR                                 NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

--changeset races:2

CREATE table IF NOT EXISTS races
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name               VARCHAR                                 NOT NULL,
    size               VARCHAR                                 NOT NULL,
    speed              INTEGER                                 NOT NULL,
    has_darkvision     BOOLEAN                                 NOT NULL,
    strength_bonus     INTEGER,
    dexterity_bonus    INTEGER,
    constitution_bonus INTEGER,
    intelligence_bonus INTEGER,
    wisdom_bonus       INTEGER,
    charisma_bonus     INTEGER,
    CONSTRAINT pk_races PRIMARY KEY (id)
);

--changeset classes:3

CREATE table IF NOT EXISTS classes
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name             VARCHAR                                 NOT NULL,
    saving_throw_one VARCHAR                                 NOT NULL,
    saving_throw_two VARCHAR                                 NOT NULL,
    CONSTRAINT pk_classes PRIMARY KEY (id)
);

--changeset abilities:4

CREATE table IF NOT EXISTS abilities
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            VARCHAR                                 NOT NULL,
    description     VARCHAR                                 NOT NULL,
    ability_source  VARCHAR                                 NOT NULL,
    is_active       BOOLEAN                                 NOT NULL,
    cost            VARCHAR                                 NOT NULL,
    requires_rest   BOOLEAN                                 NOT NULL,
    type_of_rest    VARCHAR                                 NOT NULL,
    level_available INTEGER                                 NOT NULL,
    class_source_id BIGINT references classes (id),
    race_source_id  BIGINT references races (id),
    CONSTRAINT pk_abilities PRIMARY KEY (id)
);

--changeset characters:5

CREATE table IF NOT EXISTS characters
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name              VARCHAR                                 NOT NULL,
    race_id           BIGINT                                  NOT NULL REFERENCES races (id),
    strength          INTEGER                                 NOT NULL,
    dexterity         INTEGER                                 NOT NULL,
    constitution      INTEGER                                 NOT NULL,
    intelligence      INTEGER                                 NOT NULL,
    wisdom            INTEGER                                 NOT NULL,
    charisma          INTEGER                                 NOT NULL,
    experience        BIGINT                                  NOT NULL,
    armor_class       INTEGER                                 NOT NULL,
    initiative        INTEGER                                 NOT NULL,
    main_class_id     BIGINT                                  NOT NULL REFERENCES classes (id),
    max_hp            INTEGER                                 NOT NULL,
    current_hp        INTEGER                                 NOT NULL,
    creator_id        BIGINT                                  NOT NULL REFERENCES users (id),
    is_level_up_ready BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_characters PRIMARY KEY (id)
);

--changeset proficiencies:6

CREATE table IF NOT EXISTS proficiencies
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           VARCHAR                                 NOT NULL,
    base_attribute VARCHAR,
    CONSTRAINT pk_proficiencies PRIMARY KEY (id)
);

--changeset characters_proficiencies:7

create table if not exists characters_proficiencies
(
    fk_character   bigint not null references characters (id),
    fk_proficiency bigint not null references proficiencies (id)
);

--changeset character_classes_abilities:8

create table if not exists character_classes_abilities
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    character_id   bigint                                  not null references characters (id),
    char_class_id  bigint                                  not null references classes (id),
    ability_id     bigint                                  not null references abilities (id),
    number_of_uses integer,
    CONSTRAINT pk_classes_abilities PRIMARY KEY (id)
);

--changeset character_race_abilities:9

create table if not exists character_race_abilities
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    character_id   bigint                                  not null references characters (id),
    char_race_id   bigint                                  not null references races (id),
    ability_id     bigint                                  not null references abilities (id),
    number_of_uses integer,
    CONSTRAINT pk_race_abilities PRIMARY KEY (id)
);

--changeset character_classes_level:10

create table if not exists character_classes_level
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    character_id       BIGINT                                  NOT NULL references characters (id),
    character_class_id BIGINT                                  NOT NULL references classes (id),
    char_level         INTEGER                                 NOT NULL,
    CONSTRAINT pk_ccl PRIMARY KEY (id)
);

--changeset subclasses:11

create table if not exists subclasses
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR                                 NOT NULL,
    char_class_id BIGINT                                  NOT NULL references classes (id),
    CONSTRAINT pk_subclasses PRIMARY KEY (id)
);

--changeset files:11

create table if not exists files
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR                                 NOT NULL,
    content      TEXT                                    NOT NULL,
    content_type VARCHAR                                 NOT NULL,
    character_id BIGINT                                  NOT NULL references characters (id),
    CONSTRAINT pk_files PRIMARY KEY (id)
);